name: Deploy to VPS

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Happy to be deploying"
            echo "$GITHUB_REF"
            BRANCH_NAME=$(echo "$GITHUB_REF" | sed 's|refs/heads/||')
            echo "$BRANCH_NAME"
            echo "$GITHUB_REF_NAME"
            if [ "$GITHUB_REF_NAME" = "main" ]; then
              cd ~/backend-main
              git fetch --all
              git reset --hard origin/main
              npm ci
              pm2 restart my-app-prod || pm2 start app.js --name my-app-prod
            elif [ "$GITHUB_REF_NAME" = "dev" ]; then
              cd ~/backend-dev
              git fetch --all
              git reset --hard origin/dev
              git log -1
              npm ci
              pm2 restart my-app-test || pm2 start app.js --name my-app-test
            fi
